(lang dune 2.9)
(name twentytwoday06)
(using menhir 2.1)

(generate_opam_files)

(package
  (name twentytwoday06)
  (synopsis "Advent of code 2022 day 06")
  (description "Advent of code 2022 day 06 solution in ocaml")
  (depends
    core
    menhir))
