(lang dune 2.9)
(name twentytwoday07)
(using menhir 2.1)

(generate_opam_files)

(package
  (name twentytwoday07)
  (synopsis "Advent of code 2022 day 07")
  (description "Advent of code 2022 day 07 solution in ocaml")
  (depends
    core
    menhir))
